import { pacuApi } from '@/api/pacu';
import { useRealPacu } from '@/config/apiFlags';

export type PacuStatus = 'pending'|'admitted'|'recovering'|'ready_to_discharge'|'discharged'|'voided';
export interface PacuRecordContract { operationId:string; pacuRecordId:string; status:PacuStatus; bedId?:string|null; bedName?:string|null; admittedAt?:string|null; recoveredAt?:string|null; dischargeReadyAt?:string|null; dischargedAt?:string|null; anesthesiologist?:string|null; nurse?:string|null; aldreteScore?:number|null; painScore?:number|null; nauseaVomiting?:boolean; shivering?:boolean; oxygenSupport?:string|null; airwayStatus?:string|null; vitalSummary?:string|null; dischargeDestination?:string|null; dischargeCriteriaMet?:boolean; notes?:string|null; }
export interface PacuDetailContract { operationCase:Record<string,unknown>; pacuRecord:PacuRecordContract|null; handoverSummary?:Record<string,unknown>|null; }
const mock = new Map<string,PacuDetailContract>();
type PacuAction = 'admit'|'saveRecovery'|'markReady'|'discharge'|'void';
const allowed:Record<PacuAction,string[]>={admit:['operationId','bedId','bedName','admittedAt','anesthesiologist','nurse','notes'],saveRecovery:['operationId','recoveredAt','anesthesiologist','nurse','aldreteScore','painScore','nauseaVomiting','shivering','oxygenSupport','airwayStatus','vitalSummary','notes'],markReady:['operationId','dischargeReadyAt','dischargeCriteriaMet','aldreteScore','notes'],discharge:['operationId','dischargedAt','dischargeDestination','nurse','notes'],void:['operationId','voidReason','notes']};
export function buildPacuWorkflowPayload(action:keyof typeof allowed,input:Record<string,unknown>){return Object.fromEntries(Object.entries(input).filter(([k])=>allowed[action].includes(k)));}
function mockCase(id:string){return {operationId:id,patientName:'Mock患者',operationName:'Mock手术'};}
export async function pacuDetail(operationId:string):Promise<PacuDetailContract>{if(useRealPacu())return pacuApi.detail(operationId) as Promise<PacuDetailContract>;return mock.get(operationId)??{operationCase:mockCase(operationId),pacuRecord:null,handoverSummary:null};}
export async function pacuAction(action:PacuAction,input:Record<string,unknown>):Promise<PacuDetailContract>{const payload=buildPacuWorkflowPayload(action,input);const id=String(payload.operationId??'');if(useRealPacu()){const actions={admit:pacuApi.admit,saveRecovery:pacuApi.saveRecovery,markReady:pacuApi.markReady,discharge:pacuApi.discharge,void:pacuApi.void};return actions[action](payload) as Promise<PacuDetailContract>;}const current=await pacuDetail(id);const status:PacuStatus=action==='admit'?'admitted':action==='saveRecovery'?'recovering':action==='markReady'?'ready_to_discharge':action==='discharge'?'discharged':'voided';const detail={...current,pacuRecord:{...(current.pacuRecord??{operationId:id,pacuRecordId:`mock-${id}`}),...payload,status} as PacuRecordContract};mock.set(id,detail);return detail;}
export function resetPacuWorkflowMock(){mock.clear();}
