import { beforeEach, describe, expect, it, vi } from 'vitest';
vi.mock('@/api/quality', () => ({ qualityApi: { caseList:vi.fn(), caseDetail:vi.fn(), defectCreate:vi.fn(async x=>x), defectUpdate:vi.fn(), defectSubmitRectification:vi.fn(), defectReviewResolution:vi.fn(), defectClose:vi.fn(), defectList:vi.fn() } }));
describe('quality case adapter',()=>{
 beforeEach(()=>vi.resetModules());
 it('keeps mock fallback without HTTP',async()=>{vi.stubEnv('VITE_ANESTHESIA_USE_MOCK','true');vi.stubEnv('VITE_USE_REAL_QUALITY','false');const m=await import('./qualityCaseService');expect(await m.loadQualityCases()).toEqual({list:[],items:[],total:0,page:1,pageSize:20});});
 it('uses real case path when opted in',async()=>{vi.stubEnv('VITE_ANESTHESIA_USE_MOCK','true');vi.stubEnv('VITE_USE_REAL_QUALITY','true');const api=await import('@/api/quality');vi.mocked(api.qualityApi.caseList).mockResolvedValue({list:[],total:2});const m=await import('./qualityCaseService');expect((await m.loadQualityCases()).total).toBe(2);});
 it('normalizes paged items returned by the real case API',async()=>{vi.stubEnv('VITE_ANESTHESIA_USE_MOCK','true');vi.stubEnv('VITE_USE_REAL_QUALITY','true');const api=await import('@/api/quality');vi.mocked(api.qualityApi.caseList).mockResolvedValue({items:[{operationId:'OP-1'}],list:[],total:1,page:2,pageSize:10} as never);const m=await import('./qualityCaseService');expect(await m.loadQualityCases()).toMatchObject({list:[{operationId:'OP-1'}],items:[{operationId:'OP-1'}],total:1,page:2,pageSize:10});});
 it('uses versioned controlled defect actions instead of legacy update',async()=>{const api=await import('@/api/quality');vi.mocked(api.qualityApi.defectSubmitRectification).mockResolvedValue({defectId:'D1',version:2} as never);vi.mocked(api.qualityApi.defectReviewResolution).mockResolvedValue({defectId:'D1',version:3} as never);vi.mocked(api.qualityApi.defectClose).mockResolvedValue({defectId:'D1',version:4} as never);const m=await import('./qualityCaseService');await m.submitQualityRectification({defectId:'D1',expectedVersion:1,rectification:'整改'});await m.reviewQualityDefect({defectId:'D1',expectedVersion:2,approved:true,reviewOpinion:'通过'});await m.closeQualityDefect({defectId:'D1',expectedVersion:3,reason:'关闭'});expect(api.qualityApi.defectSubmitRectification).toHaveBeenCalledWith({defectId:'D1',expectedVersion:1,rectification:'整改'});expect(api.qualityApi.defectReviewResolution).toHaveBeenCalledWith({defectId:'D1',expectedVersion:2,approved:true,reviewOpinion:'通过'});expect(api.qualityApi.defectClose).toHaveBeenCalledWith({defectId:'D1',expectedVersion:3,reason:'关闭'});expect(api.qualityApi.defectUpdate).not.toHaveBeenCalled();});
 it('never writes patient or operation master data',async()=>{const m=await import('./qualityCaseService');expect(m.defectWritePayload({operationId:'OP-1',indicatorCode:'x',patientName:'P',patientId:'1',operationName:'S',surgeryDate:'2026-07-11',operationCase:{}})).toEqual({operationId:'OP-1',indicatorCode:'x'});});
});
