import type { Component } from 'vue';
import {
  IconApps,
  IconBarChart,
  IconBookmark,
  IconCalendar,
  IconCheckCircle,
  IconClockCircle,
  IconClose,
  IconCompass,
  IconDashboard,
  IconDesktop,
  IconDownload,
  IconEdit,
  IconExclamationCircle,
  IconExperiment,
  IconEye,
  IconFile,
  IconFilter,
  IconHeart,
  IconHome,
  IconInfoCircle,
  IconList,
  IconLocation,
  IconMenu,
  IconPlus,
  IconRefresh,
  IconArrowRise,
  IconSchedule,
  IconSearch,
  IconSettings,
  IconStar,
  IconStarFill,
  IconStorage,
  IconSwap,
  IconUnorderedList,
  IconUser,
} from '@arco-design/web-vue/es/icon';

export const appIcons = {
  IconApps,
  IconBarChart,
  IconBookmark,
  IconCalendar,
  IconCheckCircle,
  IconClockCircle,
  IconClose,
  IconCompass,
  IconDashboard,
  IconDesktop,
  IconDownload,
  IconEdit,
  IconExclamationCircle,
  IconExperiment,
  IconEye,
  IconFile,
  IconFilter,
  IconHeart,
  IconHome,
  IconInfoCircle,
  IconList,
  IconLocation,
  IconMenu,
  IconPlus,
  IconRefresh,
  IconArrowRise,
  IconSchedule,
  IconSearch,
  IconSettings,
  IconStar,
  IconStarFill,
  IconStorage,
  IconSwap,
  IconUnorderedList,
  IconUser,
} as const satisfies Record<string, Component>;

export type AppIconName = keyof typeof appIcons;

export function registerAppIcons(app: { component: (name: string, comp: Component) => void }) {
  Object.entries(appIcons).forEach(([name, component]) => {
    app.component(name, component);
  });
}
