import { expect,test } from '@playwright/test';
import type { Page,Request } from '@playwright/test';
import { cleanupAssessmentPlan,generateAssessmentPlanOperationId,setupAssessmentPlan,statusAssessmentPlan } from './helpers/assessmentPlanFixture';
const realEnabled=process.env.SAMIS_ASSESSMENT_PLAN_E2E==='1';const username=process.env.SAMIS_E2E_USERNAME;const password=process.env.SAMIS_E2E_PASSWORD;
const ok=(data:unknown)=>({status:200,contentType:'application/json',body:JSON.stringify({code:0,msg:'ok',data})});const form=(r:Request)=>new URLSearchParams(r.postData()??'');
const operationCase={operationId:'OP-P08-WEB-1',patientNo:'ZY-P08-1',patientName:'真实来源患者',gender:'女',age:42,departmentName:'普外科',preoperativeDiagnosisName:'胆囊结石',operationName:'腹腔镜胆囊切除术',roomName:'OR-03',plannedStartTime:'2026-07-20 09:00:00'};
interface State{permissions:string[];assessment:any|null;assessmentHistory:any[];plan:any|null;planHistory:any[];posts:{path:string;fields:URLSearchParams}[];gets:Record<string,number>}
function makeState(permissions=['*']):State{return{permissions,assessment:null,assessmentHistory:[],plan:null,planHistory:[],posts:[],gets:{}};}
async function seed(page:Page){await page.addInitScript(()=>{sessionStorage.setItem('samis_token','p08-e2e-token');sessionStorage.setItem('samis_authorization','Bearer p08-e2e-token');sessionStorage.setItem('samis_room','OR-03');sessionStorage.setItem('samis_room_group','ANES');sessionStorage.setItem('samis_user_profile',JSON.stringify({userId:'p08-user',displayName:'P08验收医师'}));});}
function parse(v:string|null){if(v===null)return null;try{return JSON.parse(v);}catch{return v;}}
async function install(page:Page,s:State){await page.route('**/api-samis/pc/v1/**',async route=>{const req=route.request(),u=new URL(req.url()),path=u.pathname,method=req.method();if(method==='GET')s.gets[path]=(s.gets[path]??0)+1;if(method==='POST')s.posts.push({path,fields:form(req)});
  if(path.endsWith('/auth/myPermissions')){await route.fulfill(ok({permissions:s.permissions,role:s.permissions.length?'admin':'viewer'}));return;}
  if(path.endsWith('/preoperative/requestList')){await route.fulfill(ok({list:[{id:0,operationId:operationCase.operationId,status:'待接收',version:0,operationCase}],total:1}));return;}
  if(path.endsWith('/preoperative/assessmentDetail')){await route.fulfill(ok({operationCase,assessment:s.assessment,history:s.assessmentHistory,persistence:{available:true,reason:null}}));return;}
  if(path.endsWith('/preoperative/assessmentSaveDraft')){const f=form(req),next=Number(s.assessment?.version??0)+1;s.assessment={...(s.assessment??{}),operationId:operationCase.operationId,assessmentId:'PA-P08-WEB',version:next,status:'draft',asaGrade:f.get('asaGrade')||null,riskLevel:f.get('riskLevel')||null,allergyHistory:f.get('allergyHistory')||null,pastAnesthesiaHistory:f.get('pastAnesthesiaHistory')||null,airwayAssessment:f.get('airwayAssessment')||null,preMedicationAdvice:f.get('preMedicationAdvice')||null,riskSummary:f.get('riskSummary')||null,abnormalExamSummary:f.get('abnormalExamSummary')||null,medicalHistoryJson:parse(f.get('medicalHistoryJson')),surgicalHistoryJson:parse(f.get('surgicalHistoryJson')),medicationHistoryJson:parse(f.get('medicationHistoryJson')),systemAssessmentJson:parse(f.get('systemAssessmentJson')),examAbnormalitiesJson:parse(f.get('examAbnormalitiesJson')),riskFactorsJson:parse(f.get('riskFactorsJson')),recommendationsJson:parse(f.get('recommendationsJson')),airwayJson:parse(f.get('airwayJson')),fastingJson:parse(f.get('fastingJson')),dentitionJson:parse(f.get('dentitionJson')),evaluatorId:'DOC-P08',evaluatorName:'服务端评估医师',evaluatedAt:'2026-07-15 18:00:00',submittedAt:null,updatedAt:'2026-07-15 18:00:00'};await route.fulfill(ok(s.assessment));return;}
  if(path.endsWith('/preoperative/assessmentSubmit')){s.assessment={...s.assessment,status:'submitted',version:Number(s.assessment.version)+1,submittedAt:'2026-07-15 18:01:00'};s.assessmentHistory.unshift({revisionId:`REV-${s.assessment.version}`,version:s.assessment.version,submittedAt:s.assessment.submittedAt,submittedBy:'DOC-P08',revisionReason:null});await route.fulfill(ok(s.assessment));return;}
  if(path.endsWith('/preoperative/assessmentCancelSubmit')||path.endsWith('/preoperative/assessmentCreateRevision')){const f=form(req);s.assessment={...s.assessment,status:'draft',version:Number(s.assessment.version)+1,submittedAt:null,revisionReason:f.get('reason')};await route.fulfill(ok(s.assessment));return;}
  if(path.endsWith('/anesthesiaPlan/detail')){await route.fulfill(ok({operationId:operationCase.operationId,operationCase,currentPlan:s.plan,historyMeta:{total:s.planHistory.length+(s.plan?1:0),versions:[...(s.plan?[s.plan]:[]),...s.planHistory]}}));return;}
  if(path.endsWith('/anesthesiaPlan/saveDraft')){const f=form(req),next=Number(s.plan?.version??0)+1;s.plan={...(s.plan??{}),planId:'PLAN-P08',planVersionId:s.plan?.planVersionId??'PLANV-P08-1',operationId:operationCase.operationId,version:next,status:'draft',primaryMethodCode:f.get('primaryMethodCode'),primaryMethodName:f.get('primaryMethodName'),alternativeMethods:parse(f.get('alternativeMethods')),airwayPlan:parse(f.get('airwayPlan')),monitoringPlan:parse(f.get('monitoringPlan')),vascularAccessPlan:parse(f.get('vascularAccessPlan')),fluidPlanDetail:parse(f.get('fluidPlanDetail')),transfusionPlan:parse(f.get('transfusionPlan')),backupPlan:parse(f.get('backupPlan')),riskResponsePlan:parse(f.get('riskResponsePlan')),specialRisks:parse(f.get('specialRisks')),inductionPlan:f.get('inductionPlan'),maintenancePlan:f.get('maintenancePlan'),analgesiaPlan:f.get('analgesiaPlan'),postoperativeDestination:f.get('postoperativeDestination'),notes:f.get('notes'),templateCode:f.get('templateCode')||s.plan?.templateCode||null,templateVersion:f.get('templateCode')?'3':s.plan?.templateVersion??null,templateSnapshot:f.get('templateCode')?{templateCode:f.get('templateCode')}:s.plan?.templateSnapshot??null,plannerId:'DOC-P08',plannerName:'服务端计划医师',revisionReason:s.plan?.revisionReason??null,submittedAt:null,cancelledAt:null,createdAt:s.plan?.createdAt??'2026-07-15 18:02:00',updatedAt:'2026-07-15 18:02:00'};await route.fulfill(ok(s.plan));return;}
  if(path.endsWith('/anesthesiaPlan/submit')){s.plan={...s.plan,status:'submitted',version:Number(s.plan.version)+1,submittedAt:'2026-07-15 18:03:00'};s.planHistory.unshift({...s.plan});await route.fulfill(ok(s.plan));return;}
  if(path.endsWith('/anesthesiaPlan/cancel')){const f=form(req);s.plan={...s.plan,status:'cancelled',version:Number(s.plan.version)+1,revisionReason:f.get('reason'),cancelledAt:'2026-07-15 18:04:00'};await route.fulfill(ok(s.plan));return;}
  if(path.endsWith('/anesthesiaPlan/createRevision')){const f=form(req);s.plan={...s.plan,planVersionId:'PLANV-P08-2',status:'draft',version:Number(s.plan.version)+1,revisionReason:f.get('reason'),submittedAt:null,cancelledAt:null};await route.fulfill(ok(s.plan));return;}
  await route.fulfill(ok({list:[]}));});}
const formItem=(page:Page,label:string)=>page.locator('.arco-form-item').filter({hasText:label}).first();

test.describe('P08 术前评估与麻醉计划验收',()=>{
  test('真实 OperationCase 且无权限时两页零写请求',async({page})=>{const s=makeState([]);await seed(page);await install(page,s);await page.goto('/surgery/pre-visit');await expect(page.getByText('真实来源患者').first()).toBeVisible();await expect(page.getByRole('button',{name:'保存草稿'})).toBeDisabled();await page.goto('/surgery/plan');await expect(page.getByText('真实来源患者').first()).toBeVisible();await expect(page.getByRole('button',{name:'保存草稿'})).toBeDisabled();expect(s.posts.filter(x=>/assessment|anesthesiaPlan/.test(x.path))).toHaveLength(0);await expect(page.getByText(/测试患者|患者甲/)).toHaveCount(0);});

  test('丰富评估按版本保存、提交、修订并刷新保持',async({page})=>{const s=makeState(['preop.assessment.create','preop.assessment.submit']);await seed(page);await install(page,s);await page.goto('/surgery/pre-visit');await formItem(page,'ASA 分级').locator('.arco-select-view').click();await page.locator('.arco-trigger-popup:visible').getByText('III',{exact:true}).click();await formItem(page,'现病史').locator('textarea').fill('高血压');await page.getByText('气道、牙齿与禁食',{exact:true}).click();await formItem(page,'气道综合描述').locator('textarea').fill('困难气道风险');await page.getByText('异常、风险与建议',{exact:true}).click();await formItem(page,'风险因素').locator('textarea').fill('困难气道');const post=page.waitForResponse(r=>r.url().includes('assessmentSaveDraft'));const get=page.waitForResponse(r=>r.url().includes('assessmentDetail'));await page.getByRole('button',{name:'保存草稿'}).click();await post;await get;await expect(page.getByText(/草稿 · v1/)).toBeVisible();await page.reload();await page.getByText('病史与系统评估',{exact:true}).click();await expect(formItem(page,'现病史').locator('textarea')).toHaveValue('高血压');await page.getByRole('button',{name:'提交评估'}).click();await expect(page.getByText(/已提交 · v3/)).toBeVisible();await page.getByPlaceholder('撤回/修订原因').fill('调整气道预案');await page.getByRole('button',{name:'创建修订'}).click();await expect(page.getByText(/草稿 · v4/)).toBeVisible();const writes=s.posts.filter(x=>x.path.includes('/preoperative/assessment'));expect(writes.map(x=>x.fields.get('expectedVersion'))).toEqual(['0','1','2','3']);expect(JSON.parse(writes[0].fields.get('medicalHistoryJson')||'[]')).toEqual([{summary:'高血压'}]);expect(writes[0].fields.has('patientName')).toBe(false);expect(writes[0].fields.has('evaluatorName')).toBe(false);});

  test('麻醉计划结构化字段、版本、取消修订与历史完整回读',async({page})=>{const s=makeState(['plan.create','plan.submit','plan.revise']);await seed(page);await install(page,s);await page.goto('/surgery/plan');await formItem(page,'主要麻醉方式').locator('.arco-select-view').click();await page.locator('.arco-trigger-popup:visible').getByText('全身麻醉',{exact:true}).click();await formItem(page,'气道策略').locator('input').fill('气管插管');await formItem(page,'术后去向').locator('.arco-select-view').click();await page.locator('.arco-trigger-popup:visible').getByText('PACU',{exact:true}).click();await page.getByText('监测与通路',{exact:true}).click();await page.getByText('ECG',{exact:true}).click();await formItem(page,'血管通路').locator('textarea').fill('左手/PIV');await formItem(page,'风险处置').locator('textarea').fill('PONV/预防');await page.getByText('液体与输血',{exact:true}).click();await formItem(page,'液体计划').locator('textarea').fill('NS/500');const savePost=page.waitForResponse(r=>r.url().includes('anesthesiaPlan/saveDraft'));const saveGet=page.waitForResponse(r=>r.url().includes('anesthesiaPlan/detail'));await page.getByRole('button',{name:'保存草稿'}).click();await savePost;await saveGet;await expect(page.getByText(/草稿 · v1/)).toBeVisible();await page.reload();await page.getByText('监测与通路',{exact:true}).click();await expect(formItem(page,'血管通路').locator('textarea')).toHaveValue('左手/PIV');await page.getByRole('button',{name:'提交计划'}).click();await expect(page.getByText(/已提交 · v3/)).toBeVisible();await page.getByPlaceholder('取消/修订原因').fill('手术改期');await page.getByRole('button',{name:'取消计划'}).click();await expect(page.getByText(/已取消 · v4/)).toBeVisible();await page.getByPlaceholder('取消/修订原因').fill('重新规划');await page.getByRole('button',{name:'创建修订'}).click();await expect(page.getByText(/草稿 · v5/)).toBeVisible();const writes=s.posts.filter(x=>x.path.includes('/anesthesiaPlan/'));expect(writes.map(x=>x.fields.get('expectedVersion'))).toEqual(['0','1','2','3','4']);const first=writes[0].fields;expect(JSON.parse(first.get('vascularAccessPlan')||'[]')).toEqual([{summary:'左手/PIV'}]);expect(JSON.parse(first.get('fluidPlanDetail')||'[]')).toEqual([{summary:'NS/500'}]);expect(first.has('patientName')).toBe(false);expect(first.get('fluidPlan')).toBeNull();expect(first.get('bloodPreparation')).toBeNull();});

  test('真实凭据保存回读与 finally 清理（opt-in）',async({page})=>{test.skip(!realEnabled||!username||!password,'requires SAMIS_ASSESSMENT_PLAN_E2E=1 and credentials');if(!username||!password)return;const id=generateAssessmentPlanOperationId();let setup=false;try{await page.goto('/login');await page.locator('input').first().fill(username);await page.locator('input[type="password"]').fill(password);await page.getByRole('button',{name:'登录'}).click();await expect(page).not.toHaveURL(/\/login/);await setupAssessmentPlan(id);setup=true;await page.goto('/surgery/pre-visit');await page.getByPlaceholder('选择真实手术病例').click();await page.locator('.arco-trigger-popup:visible').getByText(new RegExp(id)).click();await formItem(page,'现病史').locator('textarea').fill('P08真实联调病史');const assessmentPost=page.waitForResponse(r=>r.url().includes('assessmentSaveDraft'));const assessmentGet=page.waitForResponse(r=>r.url().includes('assessmentDetail'));await page.getByRole('button',{name:'保存草稿'}).click();await assessmentPost;await assessmentGet;await page.reload();await page.getByText('病史与系统评估',{exact:true}).click();await expect(formItem(page,'现病史').locator('textarea')).toHaveValue('P08真实联调病史');await page.goto('/surgery/plan');await page.getByPlaceholder('选择真实手术病例').click();await page.locator('.arco-trigger-popup:visible').getByText(new RegExp(id)).click();await formItem(page,'主要麻醉方式').locator('.arco-select-view').click();await page.locator('.arco-trigger-popup:visible').getByText('全身麻醉',{exact:true}).click();await formItem(page,'气道策略').locator('input').fill('气管插管');await formItem(page,'术后去向').locator('.arco-select-view').click();await page.locator('.arco-trigger-popup:visible').getByText('PACU',{exact:true}).click();await page.getByText('监测与通路',{exact:true}).click();await page.getByText('ECG',{exact:true}).click();const planPost=page.waitForResponse(r=>r.url().includes('anesthesiaPlan/saveDraft'));const planGet=page.waitForResponse(r=>r.url().includes('anesthesiaPlan/detail'));await page.getByRole('button',{name:'保存草稿'}).click();await planPost;await planGet;await page.reload();await expect(page.getByText(/草稿 · v1/)).toBeVisible();}finally{if(setup)await cleanupAssessmentPlan(id);expect((await statusAssessmentPlan(id)).status).toBe('absent');}});
});
