import type { QualityCategory, QualityIndicator } from '@/types/quality';

export const indicatorGroups: Array<'全部' | QualityCategory> = ['全部', 'structure', 'process', 'outcome', 'pacu', 'postoperative', 'obstetric'];

export const qualityIndicators: QualityIndicator[] = [
  {
    code: 'AQI-DNR-01',
    name: '麻醉科医护比',
    category: 'structure',
    unit: 'ratio',
    numeratorName: '麻醉护士人数',
    denominatorName: '麻醉医师人数',
    formulaText: '麻醉护士人数 / 麻醉医师人数',
    dataSources: ['anesthesia_staff'],
    defaultChartType: 'line',
    supportDrillDown: true,
    supportDoctorAnalysis: false,
    supportRoomAnalysis: false,
    warningRule: { operator: '<', value: 1 },
  },
  {
    code: 'AQI-ACC-02',
    name: '麻醉医师人均年麻醉例次数',
    category: 'structure',
    unit: 'count',
    numeratorName: '年度麻醉总例次数',
    denominatorName: '麻醉医师人数',
    formulaText: '年度麻醉总例次数 / 麻醉医师人数',
    dataSources: ['anesthesia_case', 'anesthesia_staff'],
    defaultChartType: 'bar',
    supportDrillDown: true,
    supportDoctorAnalysis: true,
    supportRoomAnalysis: false,
  },
  {
    code: 'AQI-PAO-03',
    name: '手术室外麻醉占比',
    category: 'structure',
    unit: '%',
    numeratorName: '手术室外麻醉例数',
    denominatorName: '麻醉病例总数',
    formulaText: '手术室外麻醉例数 / 麻醉病例总数 × 100%',
    dataSources: ['anesthesia_case'],
    defaultChartType: 'mixed',
    supportDrillDown: true,
    supportDoctorAnalysis: true,
    supportRoomAnalysis: true,
  },
  {
    code: 'AQI-PVR-04',
    name: '择期手术麻醉前访视率',
    category: 'process',
    unit: '%',
    numeratorName: '完成术前访视的择期病例数',
    denominatorName: '择期手术麻醉病例数',
    formulaText: '完成术前访视的择期病例数 / 择期手术麻醉病例数 × 100%',
    dataSources: ['anesthesia_case', 'pre_anesthesia_visit'],
    defaultChartType: 'line',
    supportDrillDown: true,
    supportDoctorAnalysis: true,
    supportRoomAnalysis: true,
    warningRule: { operator: '<', value: 95 },
  },
  {
    code: 'AQI-CRB-05',
    name: '入室后手术麻醉取消率',
    category: 'process',
    unit: '‰',
    numeratorName: '入室后取消病例数',
    denominatorName: '入室病例数',
    formulaText: '入室后取消病例数 / 入室病例数 × 1000‰',
    dataSources: ['anesthesia_case'],
    defaultChartType: 'bar',
    supportDrillDown: true,
    supportDoctorAnalysis: true,
    supportRoomAnalysis: true,
    warningRule: { operator: '>', value: 10 },
  },
  {
    code: 'AQI-CRA-06',
    name: '麻醉开始后手术取消率',
    category: 'process',
    unit: '‰',
    numeratorName: '麻醉开始后取消病例数',
    denominatorName: '麻醉开始病例数',
    formulaText: '麻醉开始后取消病例数 / 麻醉开始病例数 × 1000‰',
    dataSources: ['anesthesia_case'],
    defaultChartType: 'bar',
    supportDrillDown: true,
    supportDoctorAnalysis: true,
    supportRoomAnalysis: true,
    warningRule: { operator: '>', value: 5 },
  },
  {
    code: 'AQI-TMR-07',
    name: '全身麻醉术中体温监测率',
    category: 'process',
    unit: '%',
    numeratorName: '全麻术中有体温记录病例数',
    denominatorName: '全麻病例总数',
    formulaText: '全麻术中有体温记录病例数 / 全麻病例总数 × 100%',
    dataSources: ['anesthesia_case', 'vital_sign_record'],
    defaultChartType: 'line',
    supportDrillDown: true,
    supportDoctorAnalysis: true,
    supportRoomAnalysis: true,
    warningRule: { operator: '<', value: 90 },
  },
  {
    code: 'AQI-AWR-08',
    name: '术中主动保温率',
    category: 'process',
    unit: '%',
    numeratorName: '实施主动保温病例数',
    denominatorName: '需保温手术麻醉病例数',
    formulaText: '实施主动保温病例数 / 需保温手术麻醉病例数 × 100%',
    dataSources: ['anesthesia_case', 'warming_record'],
    defaultChartType: 'line',
    supportDrillDown: true,
    supportDoctorAnalysis: true,
    supportRoomAnalysis: true,
    warningRule: { operator: '<', value: 80 },
  },
  {
    code: 'AQI-ATR-09',
    name: '术中自体血输注率',
    category: 'process',
    unit: '%',
    numeratorName: '术中自体血输注病例数',
    denominatorName: '术中输血病例数',
    formulaText: '术中自体血输注病例数 / 术中输血病例数 × 100%',
    dataSources: ['anesthesia_case', 'fluid_blood_record'],
    defaultChartType: 'bar',
    supportDrillDown: true,
    supportDoctorAnalysis: true,
    supportRoomAnalysis: true,
  },
  {
    code: 'AQI-IHT-10',
    name: '手术麻醉期间低体温发生率',
    category: 'outcome',
    unit: '%',
    numeratorName: '手术麻醉期间发生低体温病例数',
    denominatorName: '全麻病例总数',
    formulaText: '低体温病例数 / 全麻病例总数 × 100%',
    dataSources: ['anesthesia_case', 'vital_sign_record'],
    defaultChartType: 'line',
    supportDrillDown: true,
    supportDoctorAnalysis: true,
    supportRoomAnalysis: true,
    warningRule: { operator: '>', value: 5 },
  },
  {
    code: 'AQI-DII-11',
    name: '术中牙齿损伤发生率',
    category: 'outcome',
    unit: '‰',
    numeratorName: '发生牙齿损伤病例数',
    denominatorName: '气管插管全麻病例数',
    formulaText: '牙齿损伤病例数 / 气管插管全麻病例数 × 1000‰',
    dataSources: ['anesthesia_event'],
    defaultChartType: 'bar',
    supportDrillDown: true,
    supportDoctorAnalysis: true,
    supportRoomAnalysis: true,
    warningRule: { operator: '>', value: 1 },
  },
  {
    code: 'AQI-AAR-12',
    name: '麻醉期间严重反流误吸发生率',
    category: 'outcome',
    unit: '‰',
    numeratorName: '严重反流误吸事件病例数',
    denominatorName: '手术麻醉病例总数',
    formulaText: '严重反流误吸病例数 / 手术麻醉病例总数 × 1000‰',
    dataSources: ['anesthesia_event'],
    defaultChartType: 'bar',
    supportDrillDown: true,
    supportDoctorAnalysis: true,
    supportRoomAnalysis: true,
    warningRule: { operator: '>', value: 1 },
  },
  {
    code: 'AQI-UPA-13',
    name: '计划外建立人工气道发生率',
    category: 'outcome',
    unit: '‰',
    numeratorName: '计划外建立人工气道病例数',
    denominatorName: '非计划内气管插管分母病例数',
    formulaText: '计划外建立人工气道病例数 / 适用分母病例数 × 1000‰',
    dataSources: ['airway_record', 'anesthesia_event'],
    defaultChartType: 'bar',
    supportDrillDown: true,
    supportDoctorAnalysis: true,
    supportRoomAnalysis: true,
    warningRule: { operator: '>', value: 1 },
  },
  {
    code: 'AQI-ICA-14',
    name: '术中心脏骤停率',
    category: 'outcome',
    unit: '‰',
    numeratorName: '术中心脏骤停病例数',
    denominatorName: '手术麻醉病例总数',
    formulaText: '术中心脏骤停病例数 / 手术麻醉病例总数 × 1000‰',
    dataSources: ['anesthesia_event'],
    defaultChartType: 'bar',
    supportDrillDown: true,
    supportDoctorAnalysis: true,
    supportRoomAnalysis: true,
    warningRule: { operator: '>', value: 0 },
  },
  {
    code: 'AQI-ASA-15',
    name: '麻醉期间严重过敏反应发生率',
    category: 'outcome',
    unit: '‰',
    numeratorName: '严重过敏反应病例数',
    denominatorName: '手术麻醉病例总数',
    formulaText: '严重过敏反应病例数 / 手术麻醉病例总数 × 1000‰',
    dataSources: ['anesthesia_event', 'anesthesia_medication'],
    defaultChartType: 'bar',
    supportDrillDown: true,
    supportDoctorAnalysis: true,
    supportRoomAnalysis: true,
    warningRule: { operator: '>', value: 1 },
  },
  {
    code: 'AQI-AWR-16',
    name: '全身麻醉术中知晓发生率',
    category: 'outcome',
    unit: '‰',
    numeratorName: '全麻术中知晓病例数',
    denominatorName: '全麻病例总数',
    formulaText: '全麻术中知晓病例数 / 全麻病例总数 × 1000‰',
    dataSources: ['postoperative_followup'],
    defaultChartType: 'bar',
    supportDrillDown: true,
    supportDoctorAnalysis: true,
    supportRoomAnalysis: true,
    warningRule: { operator: '>', value: 1 },
  },
  {
    code: 'AQI-PHT-17',
    name: 'PACU入室低体温发生率',
    category: 'pacu',
    unit: '%',
    numeratorName: 'PACU入室低体温病例数',
    denominatorName: '入PACU病例总数',
    formulaText: 'PACU入室低体温病例数 / 入PACU病例总数 × 100%',
    dataSources: ['pacu_record'],
    defaultChartType: 'line',
    supportDrillDown: true,
    supportDoctorAnalysis: true,
    supportRoomAnalysis: true,
    warningRule: { operator: '>', value: 5 },
  },
  {
    code: 'AQI-PDR-18',
    name: '麻醉后PACU转出延迟率',
    category: 'pacu',
    unit: '%',
    numeratorName: 'PACU停留超过2小时病例数',
    denominatorName: '入PACU病例总数',
    formulaText: 'PACU转出延迟病例数 / 入PACU病例总数 × 100%',
    dataSources: ['pacu_record'],
    defaultChartType: 'line',
    supportDrillDown: true,
    supportDoctorAnalysis: true,
    supportRoomAnalysis: true,
    warningRule: { operator: '>', value: 10 },
  },
  {
    code: 'AQI-URI-19',
    name: '非计划二次气管插管率',
    category: 'pacu',
    unit: '‰',
    numeratorName: '非计划二次气管插管病例数',
    denominatorName: '拔管病例数',
    formulaText: '非计划二次气管插管病例数 / 拔管病例数 × 1000‰',
    dataSources: ['pacu_record', 'airway_record'],
    defaultChartType: 'bar',
    supportDrillDown: true,
    supportDoctorAnalysis: true,
    supportRoomAnalysis: true,
    warningRule: { operator: '>', value: 1 },
  },
  {
    code: 'AQI-UICU-20',
    name: '非计划转入ICU率',
    category: 'pacu',
    unit: '%',
    numeratorName: '非计划转入ICU病例数',
    denominatorName: '手术麻醉病例总数',
    formulaText: '非计划转入ICU病例数 / 手术麻醉病例总数 × 100%',
    dataSources: ['anesthesia_case', 'anesthesia_event'],
    defaultChartType: 'line',
    supportDrillDown: true,
    supportDoctorAnalysis: true,
    supportRoomAnalysis: true,
    warningRule: { operator: '>', value: 2 },
  },
  {
    code: 'AQI-PAS-21',
    name: '术后镇痛满意率',
    category: 'postoperative',
    unit: '%',
    numeratorName: 'VAS≤3的术后镇痛随访病例数',
    denominatorName: '术后镇痛随访病例数',
    formulaText: 'VAS≤3病例数 / 术后镇痛随访病例数 × 100%',
    dataSources: ['postoperative_followup'],
    defaultChartType: 'line',
    supportDrillDown: true,
    supportDoctorAnalysis: true,
    supportRoomAnalysis: true,
    warningRule: { operator: '<', value: 90 },
  },
  {
    code: 'AQI-RNC-22',
    name: '区域阻滞麻醉后严重神经并发症发生率',
    category: 'postoperative',
    unit: '‰',
    numeratorName: '区域阻滞后严重神经并发症病例数',
    denominatorName: '区域阻滞麻醉病例数',
    formulaText: '严重神经并发症病例数 / 区域阻滞麻醉病例数 × 1000‰',
    dataSources: ['postoperative_followup'],
    defaultChartType: 'bar',
    supportDrillDown: true,
    supportDoctorAnalysis: true,
    supportRoomAnalysis: true,
    warningRule: { operator: '>', value: 1 },
  },
  {
    code: 'AQI-HRS-23',
    name: '全身麻醉气管插管拔管后声音嘶哑发生率',
    category: 'postoperative',
    unit: '%',
    numeratorName: '拔管后声音嘶哑病例数',
    denominatorName: '全麻气管插管病例数',
    formulaText: '声音嘶哑病例数 / 全麻气管插管病例数 × 100%',
    dataSources: ['postoperative_followup', 'airway_record'],
    defaultChartType: 'line',
    supportDrillDown: true,
    supportDoctorAnalysis: true,
    supportRoomAnalysis: true,
    warningRule: { operator: '>', value: 10 },
  },
  {
    code: 'AQI-NCC-24',
    name: '麻醉后新发昏迷发生率',
    category: 'postoperative',
    unit: '‰',
    numeratorName: '麻醉后新发昏迷病例数',
    denominatorName: '手术麻醉病例总数',
    formulaText: '麻醉后新发昏迷病例数 / 手术麻醉病例总数 × 1000‰',
    dataSources: ['postoperative_followup'],
    defaultChartType: 'bar',
    supportDrillDown: true,
    supportDoctorAnalysis: true,
    supportRoomAnalysis: true,
    warningRule: { operator: '>', value: 1 },
  },
  {
    code: 'AQI-D24-25',
    name: '麻醉后24小时内患者死亡率',
    category: 'postoperative',
    unit: '‰',
    numeratorName: '麻醉后24小时内死亡病例数',
    denominatorName: '手术麻醉病例总数',
    formulaText: '麻醉后24小时内死亡病例数 / 手术麻醉病例总数 × 1000‰',
    dataSources: ['postoperative_followup'],
    defaultChartType: 'bar',
    supportDrillDown: true,
    supportDoctorAnalysis: true,
    supportRoomAnalysis: true,
    warningRule: { operator: '>', value: 0 },
  },
  {
    code: 'AQI-LEA-26',
    name: '阴道分娩椎管内麻醉使用率',
    category: 'obstetric',
    unit: '%',
    numeratorName: '阴道分娩椎管内麻醉例数',
    denominatorName: '阴道分娩例数',
    formulaText: '阴道分娩椎管内麻醉例数 / 阴道分娩例数 × 100%',
    dataSources: ['anesthesia_case'],
    defaultChartType: 'line',
    supportDrillDown: true,
    supportDoctorAnalysis: true,
    supportRoomAnalysis: true,
    warningRule: { operator: '<', value: 60 },
  },
];
