import type { QualityIndicator, QualityPresentation } from '@/types/quality';

type PresentationRecord = Record<string, QualityPresentation>;

const rateDimensions = ['按科室查看', '按麻醉医生查看', '按手术间查看'];
const eventDimensions = ['按事件类型查看', '按麻醉医生查看', '按手术间查看'];
const pacuDimensions = ['按PACU班次查看', '按转出地点查看', '按麻醉医生查看'];

export const qualityPresentationByCode: PresentationRecord = {
  'AQI-DNR-01': {
    displayChartType: 'donut',
    trendChartMode: 'structure',
    numeratorLabel: '麻醉护士人数',
    denominatorLabel: '麻醉医师人数',
    numeratorShortLabel: '护士数',
    denominatorShortLabel: '医师数',
    metricInterpretation: '用于观察麻醉科护士与医师配置是否匹配（常见展示为护士:医师，如 4:1），是单院麻醉服务能力和排班安全性的结构性指标。',
    detailDimensionSuggestions: ['按人员类别查看', '按职称结构查看'],
  },
  'AQI-ACC-02': {
    displayChartType: 'bar',
    trendChartMode: 'distribution',
    numeratorLabel: '年度麻醉总例次数',
    denominatorLabel: '纳入统计的麻醉医师人数',
    numeratorShortLabel: '麻醉例次',
    denominatorShortLabel: '医师数',
    metricInterpretation: '用于衡量麻醉医师年度服务量，辅助判断工作负荷和人力配置压力。',
    detailDimensionSuggestions: ['按麻醉医生查看', '按科室查看'],
  },
  'AQI-PAO-03': {
    displayChartType: 'donut',
    trendChartMode: 'structure',
    numeratorLabel: '手术室外麻醉例数',
    denominatorLabel: '全部麻醉病例数',
    numeratorShortLabel: '室外麻醉',
    denominatorShortLabel: '麻醉总例',
    metricInterpretation: '用于观察内镜中心、介入室、产房等手术室外麻醉服务在全部麻醉业务中的占比。',
    detailDimensionSuggestions: ['按麻醉地点查看', '按麻醉方式查看'],
  },
  'AQI-PVR-04': {
    displayChartType: 'combo',
    trendChartMode: 'monthlyTrend',
    numeratorLabel: '完成术前访视的择期病例数',
    denominatorLabel: '择期手术麻醉病例数',
    numeratorShortLabel: '已访视病例',
    denominatorShortLabel: '择期病例',
    metricInterpretation: '表示择期手术患者中，麻醉前完成访视、评估和知情沟通的病例比例。',
    detailDimensionSuggestions: rateDimensions,
  },
  'AQI-CRB-05': {
    displayChartType: 'combo',
    trendChartMode: 'monthlyTrend',
    numeratorLabel: '入室后取消病例数',
    denominatorLabel: '入室病例数',
    numeratorShortLabel: '入室后取消',
    denominatorShortLabel: '入室病例',
    metricInterpretation: '表示已进入手术间的患者中，最终取消手术麻醉的病例占全部入室病例的比例。',
    detailDimensionSuggestions: rateDimensions,
  },
  'AQI-CRA-06': {
    displayChartType: 'combo',
    trendChartMode: 'monthlyTrend',
    numeratorLabel: '麻醉开始后取消病例数',
    denominatorLabel: '麻醉开始病例数',
    numeratorShortLabel: '麻醉后取消',
    denominatorShortLabel: '麻醉开始',
    metricInterpretation: '表示已经开始麻醉后仍取消手术的病例占全部麻醉开始病例的比例，重点反映术前核查和流程协同问题。',
    detailDimensionSuggestions: rateDimensions,
  },
  'AQI-TMR-07': {
    displayChartType: 'combo',
    trendChartMode: 'monthlyTrend',
    numeratorLabel: '全麻术中有体温记录病例数',
    denominatorLabel: '全麻病例总数',
    numeratorShortLabel: '有体温记录',
    denominatorShortLabel: '全麻病例',
    metricInterpretation: '表示全身麻醉病例中，术中按要求记录体温的覆盖情况。',
    detailDimensionSuggestions: rateDimensions,
  },
  'AQI-AWR-08': {
    displayChartType: 'combo',
    trendChartMode: 'monthlyTrend',
    numeratorLabel: '实施主动保温病例数',
    denominatorLabel: '需保温手术麻醉病例数',
    numeratorShortLabel: '主动保温',
    denominatorShortLabel: '需保温病例',
    metricInterpretation: '用于观察需保温病例中主动保温措施的落实情况。',
    detailDimensionSuggestions: rateDimensions,
  },
  'AQI-ATR-09': {
    displayChartType: 'combo',
    trendChartMode: 'monthlyTrend',
    numeratorLabel: '术中自体血输注病例数',
    denominatorLabel: '术中输血病例数',
    numeratorShortLabel: '自体血输注',
    denominatorShortLabel: '术中输血',
    metricInterpretation: '用于观察符合条件病例中自体血回输应用情况，辅助评估围术期输血管理。',
    detailDimensionSuggestions: ['按手术类型查看', '按科室查看', '按手术间查看'],
  },
  'AQI-IHT-10': {
    displayChartType: 'combo',
    trendChartMode: 'monthlyTrend',
    numeratorLabel: '手术麻醉期间低体温病例数',
    denominatorLabel: '全麻病例总数',
    numeratorShortLabel: '低体温病例',
    denominatorShortLabel: '全麻病例',
    metricInterpretation: '表示全麻病例中术中或麻醉恢复期发生低体温的比例，是低体温防控效果的结果指标。',
    detailDimensionSuggestions: eventDimensions,
  },
  'AQI-DII-11': {
    displayChartType: 'combo',
    trendChartMode: 'monthlyTrend',
    numeratorLabel: '发生牙齿损伤病例数',
    denominatorLabel: '气管插管全麻病例数',
    numeratorShortLabel: '牙齿损伤',
    denominatorShortLabel: '插管全麻',
    metricInterpretation: '用于观察气道操作相关牙齿损伤事件发生情况。',
    detailDimensionSuggestions: eventDimensions,
  },
  'AQI-AAR-12': {
    displayChartType: 'combo',
    trendChartMode: 'monthlyTrend',
    numeratorLabel: '严重反流误吸事件病例数',
    denominatorLabel: '手术麻醉病例总数',
    numeratorShortLabel: '反流误吸',
    denominatorShortLabel: '手术麻醉',
    metricInterpretation: '用于观察麻醉期间严重反流误吸事件发生情况。',
    detailDimensionSuggestions: eventDimensions,
  },
  'AQI-UPA-13': {
    displayChartType: 'combo',
    trendChartMode: 'monthlyTrend',
    numeratorLabel: '计划外建立人工气道病例数',
    denominatorLabel: '手术麻醉病例总数',
    numeratorShortLabel: '计划外气道',
    denominatorShortLabel: '手术麻醉',
    metricInterpretation: '用于观察围麻醉期计划外建立人工气道事件，反映气道评估和风险处置质量。',
    detailDimensionSuggestions: eventDimensions,
  },
  'AQI-ICA-14': {
    displayChartType: 'combo',
    trendChartMode: 'monthlyTrend',
    numeratorLabel: '术中心脏骤停病例数',
    denominatorLabel: '手术麻醉病例总数',
    numeratorShortLabel: '心脏骤停',
    denominatorShortLabel: '手术麻醉',
    metricInterpretation: '用于观察手术麻醉期间心脏骤停事件发生情况。',
    detailDimensionSuggestions: eventDimensions,
  },
  'AQI-ASA-15': {
    displayChartType: 'combo',
    trendChartMode: 'monthlyTrend',
    numeratorLabel: '严重过敏反应病例数',
    denominatorLabel: '手术麻醉病例总数',
    numeratorShortLabel: '严重过敏',
    denominatorShortLabel: '手术麻醉',
    metricInterpretation: '用于观察麻醉期间严重过敏反应事件发生情况及抢救处置质量。',
    detailDimensionSuggestions: eventDimensions,
  },
  'AQI-AWR-16': {
    displayChartType: 'combo',
    trendChartMode: 'monthlyTrend',
    numeratorLabel: '全麻术中知晓病例数',
    denominatorLabel: '全麻病例总数',
    numeratorShortLabel: '术中知晓',
    denominatorShortLabel: '全麻病例',
    metricInterpretation: '用于观察全身麻醉患者术中知晓事件发生情况，需结合术后随访确认。',
    detailDimensionSuggestions: ['按麻醉方式查看', '按麻醉医生查看', '按手术类型查看'],
  },
  'AQI-PHT-17': {
    displayChartType: 'combo',
    trendChartMode: 'monthlyTrend',
    numeratorLabel: 'PACU入室低体温病例数',
    denominatorLabel: '入PACU病例总数',
    numeratorShortLabel: '入PACU低体温',
    denominatorShortLabel: '入PACU病例',
    metricInterpretation: '表示入PACU患者中首次体温低于36℃的比例，反映术中保温和转运保温效果。',
    detailDimensionSuggestions: pacuDimensions,
  },
  'AQI-PDR-18': {
    displayChartType: 'combo',
    trendChartMode: 'monthlyTrend',
    numeratorLabel: 'PACU停留超过2小时病例数',
    denominatorLabel: '入PACU病例总数',
    numeratorShortLabel: '转出延迟',
    denominatorShortLabel: '入PACU病例',
    metricInterpretation: '表示PACU停留超过2小时的病例比例，用于发现苏醒延迟、交接或床位流转问题。',
    detailDimensionSuggestions: pacuDimensions,
  },
  'AQI-URI-19': {
    displayChartType: 'combo',
    trendChartMode: 'monthlyTrend',
    numeratorLabel: '非计划二次气管插管病例数',
    denominatorLabel: '拔管病例数',
    numeratorShortLabel: '二次插管',
    denominatorShortLabel: '拔管病例',
    metricInterpretation: '用于观察麻醉后非计划二次插管事件，反映拔管评估和恢复期呼吸安全。',
    detailDimensionSuggestions: pacuDimensions,
  },
  'AQI-UICU-20': {
    displayChartType: 'combo',
    trendChartMode: 'monthlyTrend',
    numeratorLabel: '非计划转入ICU病例数',
    denominatorLabel: '手术麻醉病例总数',
    numeratorShortLabel: '非计划转ICU',
    denominatorShortLabel: '手术麻醉',
    metricInterpretation: '表示麻醉后非计划转入ICU的病例比例，是围术期安全事件和术后去向管理的重要结果指标。',
    detailDimensionSuggestions: eventDimensions,
  },
  'AQI-PAS-21': {
    displayChartType: 'combo',
    trendChartMode: 'monthlyTrend',
    numeratorLabel: 'VAS≤3的术后镇痛随访病例数',
    denominatorLabel: '术后镇痛随访病例数',
    numeratorShortLabel: '镇痛满意',
    denominatorShortLabel: '镇痛随访',
    metricInterpretation: '表示术后镇痛随访中VAS评分≤3的病例比例，用于观察术后镇痛服务效果。',
    detailDimensionSuggestions: ['按科室查看', '按镇痛方式查看', '按麻醉医生查看'],
  },
  'AQI-RNC-22': {
    displayChartType: 'combo',
    trendChartMode: 'monthlyTrend',
    numeratorLabel: '区域阻滞后严重神经并发症病例数',
    denominatorLabel: '区域阻滞麻醉病例数',
    numeratorShortLabel: '神经并发症',
    denominatorShortLabel: '区域阻滞',
    metricInterpretation: '用于观察区域阻滞麻醉后严重神经并发症发生情况。',
    detailDimensionSuggestions: ['按阻滞部位查看', '按麻醉医生查看', '按科室查看'],
  },
  'AQI-HRS-23': {
    displayChartType: 'combo',
    trendChartMode: 'monthlyTrend',
    numeratorLabel: '拔管后声音嘶哑病例数',
    denominatorLabel: '全麻气管插管病例数',
    numeratorShortLabel: '声音嘶哑',
    denominatorShortLabel: '插管全麻',
    metricInterpretation: '表示全麻气管插管拔管后发生声音嘶哑的病例比例，需结合随访判断持续时间。',
    detailDimensionSuggestions: ['按气道工具查看', '按麻醉医生查看', '按手术类型查看'],
  },
  'AQI-NCC-24': {
    displayChartType: 'combo',
    trendChartMode: 'monthlyTrend',
    numeratorLabel: '麻醉后新发昏迷病例数',
    denominatorLabel: '手术麻醉病例总数',
    numeratorShortLabel: '新发昏迷',
    denominatorShortLabel: '手术麻醉',
    metricInterpretation: '用于观察麻醉后新发昏迷事件，重点关注麻醉、手术和基础疾病共同影响。',
    detailDimensionSuggestions: eventDimensions,
  },
  'AQI-D24-25': {
    displayChartType: 'combo',
    trendChartMode: 'monthlyTrend',
    numeratorLabel: '麻醉后24小时内死亡病例数',
    denominatorLabel: '手术麻醉病例总数',
    numeratorShortLabel: '24小时死亡',
    denominatorShortLabel: '手术麻醉',
    metricInterpretation: '用于观察麻醉后24小时内死亡事件，需结合病情严重程度和手术风险进行复核。',
    detailDimensionSuggestions: eventDimensions,
  },
  'AQI-LEA-26': {
    displayChartType: 'combo',
    trendChartMode: 'monthlyTrend',
    numeratorLabel: '阴道分娩椎管内麻醉例数',
    denominatorLabel: '阴道分娩例数',
    numeratorShortLabel: '椎管内分娩镇痛',
    denominatorShortLabel: '阴道分娩',
    metricInterpretation: '表示阴道分娩产妇中使用椎管内麻醉或镇痛的比例，反映产科镇痛服务覆盖情况。',
    detailDimensionSuggestions: ['按产房查看', '按班次查看', '按麻醉医生查看'],
  },
};

export function presentationForIndicator(indicator: QualityIndicator): QualityPresentation {
  return (
    qualityPresentationByCode[indicator.code] ?? {
      displayChartType: indicator.category === 'structure' ? 'donut' : 'combo',
      trendChartMode: indicator.category === 'structure' ? 'structure' : 'monthlyTrend',
      numeratorLabel: indicator.numeratorName,
      denominatorLabel: indicator.denominatorName,
      numeratorShortLabel: indicator.numeratorName,
      denominatorShortLabel: indicator.denominatorName,
      metricInterpretation: '用于观察该麻醉质控指标在当前统计周期内的表现，并支持病例穿透和维度分析。',
      detailDimensionSuggestions: rateDimensions,
    }
  );
}
