<template>
  <ModulePageShell title="特殊事件/抢救记录" description="关键事件、抢救事件和抢救动作直接读取服务端关系表">
    <template #toolbar><a-select v-model="selected" :loading="loadingCases" style="width:340px" placeholder="选择手术病例"><a-option v-for="item in cases" :key="item.operationId!" :value="item.operationId!">{{ item.patientName || '—' }} · {{ item.operationName || item.plannedOperationName || '—' }}</a-option></a-select><a-button :loading="loading" @click="load">刷新</a-button><a-button type="primary" :disabled="!selected" @click="router.push(`/surgery/record/${selected}`)">进入记录单录入</a-button></template>
    <a-alert v-if="error" type="error" show-icon style="margin-bottom:12px">{{ error }}</a-alert>
    <a-card class="section-card" :bordered="false" title="关键事件">
      <a-table v-if="events.length || loading" :data="events" :loading="loading" :pagination="false" row-key="localId"><template #columns><a-table-column title="时间" data-index="eventTime" /><a-table-column title="事件" data-index="eventName" /><a-table-column title="阶段" data-index="stage" /><a-table-column title="严重程度" data-index="severity" /><a-table-column title="描述" data-index="description" /><a-table-column title="处置" data-index="treatment" /></template></a-table><EmptyState v-else title="暂无真实关键事件" icon="IconCheckCircle" />
    </a-card>
    <a-card class="section-card" :bordered="false" title="抢救事件与动作">
      <a-descriptions :column="3" bordered size="small"><a-descriptions-item label="抢救事件">{{ rescueEvents.length }}</a-descriptions-item><a-descriptions-item label="抢救动作">{{ rescueActions.length }}</a-descriptions-item><a-descriptions-item label="来源">服务端结构化关系表</a-descriptions-item></a-descriptions>
    </a-card>
  </ModulePageShell>
</template>
<script setup lang="ts">
import { onMounted, ref, watch } from 'vue';import { useRouter } from 'vue-router';import ModulePageShell from '@/components/shared/ModulePageShell.vue';import EmptyState from '@/components/shared/EmptyState.vue';import { loadOperationCases } from '@/services/preoperative/preoperativeFiveFlowsService';import { fetchRecordDetail, type RecordDetailStructuredEntity, type RecordDetailTimelineEvent } from '@/services/anesthesia/anesthesiaRecordHydrate';import type { OperationCase } from '@/services/anesthesia/adapters/operationInfoAdapter';
const router=useRouter();const cases=ref<OperationCase[]>([]);const selected=ref('');const events=ref<RecordDetailTimelineEvent[]>([]);const rescueEvents=ref<RecordDetailStructuredEntity[]>([]);const rescueActions=ref<RecordDetailStructuredEntity[]>([]);const loadingCases=ref(false);const loading=ref(false);const error=ref('');async function loadCases(){loadingCases.value=true;try{cases.value=await loadOperationCases();selected.value=selected.value||String(cases.value[0]?.operationId??'');}catch(e){error.value=e instanceof Error?e.message:'加载病例失败';}finally{loadingCases.value=false;}}async function load(){if(!selected.value){events.value=[];return;}loading.value=true;error.value='';try{const record=(await fetchRecordDetail(selected.value)).record;events.value=record?.timelineEvents??[];rescueEvents.value=record?.rescueEvents??[];rescueActions.value=record?.rescueActions??[];}catch(e){events.value=[];rescueEvents.value=[];rescueActions.value=[];error.value=e instanceof Error?e.message:'加载事件失败';}finally{loading.value=false;}}watch(selected,load);onMounted(loadCases);
</script>
