<template>
  <ModulePageShell title="术中用药" description="直接读取麻醉记录关系表；录入统一进入麻醉记录单和离线同步队列">
    <template #toolbar><a-select v-model="selected" :loading="loadingCases" style="width:340px" placeholder="选择手术病例"><a-option v-for="item in cases" :key="item.operationId!" :value="item.operationId!">{{ item.patientName || '—' }} · {{ item.operationName || item.plannedOperationName || '—' }}</a-option></a-select><a-button :loading="loading" @click="load">刷新</a-button><a-button type="primary" :disabled="!selected" @click="router.push(`/surgery/record/${selected}`)">进入记录单录入</a-button></template>
    <a-alert v-if="error" type="error" show-icon style="margin-bottom:12px">{{ error }}</a-alert>
    <a-card class="section-card" :bordered="false" title="服务端用药明细">
      <a-table v-if="rows.length || loading" :data="rows" :loading="loading" :pagination="false" row-key="localId"><template #columns><a-table-column title="时间" data-index="eventTime" /><a-table-column title="药品" data-index="drugName" /><a-table-column title="模式" data-index="mode" /><a-table-column title="剂量"><template #cell="{record}">{{ record.dose ?? '—' }} {{ record.doseUnit || '' }}</template></a-table-column><a-table-column title="速率"><template #cell="{record}">{{ record.rate || '—' }} {{ record.rateUnit || '' }}</template></a-table-column><a-table-column title="途径" data-index="route" /><a-table-column title="执行人" data-index="executor" /><a-table-column title="版本" data-index="syncVersion" /></template></a-table>
      <EmptyState v-else title="暂无真实用药记录" description="服务端关系表为空，页面不会从本地病例池补造数据" icon="IconExperiment" />
    </a-card>
  </ModulePageShell>
</template>
<script setup lang="ts">
import { onMounted, ref, watch } from 'vue';import { useRouter } from 'vue-router';import ModulePageShell from '@/components/shared/ModulePageShell.vue';import EmptyState from '@/components/shared/EmptyState.vue';import { loadOperationCases } from '@/services/preoperative/preoperativeFiveFlowsService';import { fetchRecordDetail, type RecordDetailMedication } from '@/services/anesthesia/anesthesiaRecordHydrate';import type { OperationCase } from '@/services/anesthesia/adapters/operationInfoAdapter';
const router=useRouter();const cases=ref<OperationCase[]>([]);const selected=ref('');const rows=ref<(RecordDetailMedication&{syncVersion?:number})[]>([]);const loadingCases=ref(false);const loading=ref(false);const error=ref('');async function loadCases(){loadingCases.value=true;try{cases.value=await loadOperationCases();selected.value=selected.value||String(cases.value[0]?.operationId??'');}catch(e){error.value=e instanceof Error?e.message:'加载病例失败';}finally{loadingCases.value=false;}}async function load(){if(!selected.value){rows.value=[];return;}loading.value=true;error.value='';try{rows.value=(await fetchRecordDetail(selected.value)).record?.medications??[];}catch(e){rows.value=[];error.value=e instanceof Error?e.message:'加载用药失败';}finally{loading.value=false;}}watch(selected,load);onMounted(loadCases);
</script>
