<template>
  <ModulePageShell title="输液输血" description="液体、输血记录和输血核对均读取服务端关系表">
    <template #toolbar><a-select v-model="selected" :loading="loadingCases" style="width:340px" placeholder="选择手术病例"><a-option v-for="item in cases" :key="item.operationId!" :value="item.operationId!">{{ item.patientName || '—' }} · {{ item.operationName || item.plannedOperationName || '—' }}</a-option></a-select><a-button :loading="loading" @click="load">刷新</a-button><a-button type="primary" :disabled="!selected" @click="router.push(`/surgery/record/${selected}`)">进入记录单录入</a-button></template>
    <a-alert v-if="error" type="error" show-icon style="margin-bottom:12px">{{ error }}</a-alert>
    <a-card class="section-card" :bordered="false" title="液体记录">
      <a-table v-if="fluids.length || loading" :data="fluids" :loading="loading" :pagination="false" row-key="localId"><template #columns><a-table-column title="名称" data-index="fluidName" /><a-table-column title="类别" data-index="category" /><a-table-column title="容量"><template #cell="{record}">{{ record.volume ?? '—' }} {{ record.unit || '' }}</template></a-table-column><a-table-column title="开始" data-index="startTime" /><a-table-column title="结束" data-index="endTime" /></template></a-table><EmptyState v-else title="暂无真实液体记录" icon="IconSwap" />
    </a-card>
    <a-card class="section-card" :bordered="false" title="输血记录与核对">
      <a-table v-if="transfusions.length" :data="transfusions" :pagination="false" row-key="localId"><template #columns><a-table-column title="血制品" data-index="productName" /><a-table-column title="容量"><template #cell="{record}">{{ record.volume ?? '—' }} {{ record.unit || '' }}</template></a-table-column><a-table-column title="开始" data-index="startTime" /><a-table-column title="结束" data-index="endTime" /><a-table-column title="输血反应" data-index="reaction" /></template></a-table><EmptyState v-else title="暂无真实输血记录" icon="IconHeart" />
    </a-card>
  </ModulePageShell>
</template>
<script setup lang="ts">
import { onMounted, ref, watch } from 'vue';import { useRouter } from 'vue-router';import ModulePageShell from '@/components/shared/ModulePageShell.vue';import EmptyState from '@/components/shared/EmptyState.vue';import { loadOperationCases } from '@/services/preoperative/preoperativeFiveFlowsService';import { fetchRecordDetail, type RecordDetailFluid, type RecordDetailTransfusion } from '@/services/anesthesia/anesthesiaRecordHydrate';import type { OperationCase } from '@/services/anesthesia/adapters/operationInfoAdapter';
const router=useRouter();const cases=ref<OperationCase[]>([]);const selected=ref('');const fluids=ref<RecordDetailFluid[]>([]);const transfusions=ref<RecordDetailTransfusion[]>([]);const loadingCases=ref(false);const loading=ref(false);const error=ref('');async function loadCases(){loadingCases.value=true;try{cases.value=await loadOperationCases();selected.value=selected.value||String(cases.value[0]?.operationId??'');}catch(e){error.value=e instanceof Error?e.message:'加载病例失败';}finally{loadingCases.value=false;}}async function load(){if(!selected.value){fluids.value=[];transfusions.value=[];return;}loading.value=true;error.value='';try{const record=(await fetchRecordDetail(selected.value)).record;fluids.value=record?.fluids??[];transfusions.value=record?.transfusions??[];}catch(e){fluids.value=[];transfusions.value=[];error.value=e instanceof Error?e.message:'加载输液输血失败';}finally{loading.value=false;}}watch(selected,load);onMounted(loadCases);
</script>
