import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
const execFileAsync=promisify(execFile); const container=process.env.SAMIS_E2E_FIXTURE_CONTAINER??'1Panel-php8-B01L'; const workdir='/www/sites/api.cnwenhui.cn/index';
async function run(code:string):Promise<Record<string,unknown>>{const {stdout}=await execFileAsync('docker',['exec','-w',workdir,container,'php','-r',code],{encoding:'utf8'});return JSON.parse(stdout.trim().split(/\r?\n/).pop()??'{}');}
const bootstrap=`require 'vendor/autoload.php'; require 'tests/support/OperationScheduleFixture.php'; require 'tests/support/AnesthesiaPlanFixture.php'; (new think\\App())->initialize();`;
export function generateAssessmentPlanOperationId(){return `OP-E2E-P08-WEB-${Date.now().toString(36)}${Math.random().toString(36).slice(2,5)}`;}
export async function setupAssessmentPlan(operationId:string){return run(`${bootstrap} echo json_encode(tests\\support\\OperationScheduleFixture::setup(${JSON.stringify(operationId)}, ['OPERATINGROOM_CODE'=>'OP-E2E-OR','OPERATINGROOM_NAME'=>'E2E手术间','ROOM_GROUP'=>'OP-E2E-GROUP','ROOM_GROUP_NAME'=>'E2E手术部']), JSON_UNESCAPED_UNICODE);`);}
export async function cleanupAssessmentPlan(operationId:string){return run(`${bootstrap} $id=${JSON.stringify(operationId)}; (new app\\samis\\domain\\preoperative\\repository\\AnesPreopAssessmentRepository())->cleanupTestRecord($id); tests\\support\\AnesthesiaPlanFixture::cleanup($id); $r=tests\\support\\OperationScheduleFixture::cleanup($id); echo json_encode($r, JSON_UNESCAPED_UNICODE);`);}
export async function statusAssessmentPlan(operationId:string){return run(`${bootstrap} $id=${JSON.stringify(operationId)}; $a=(new app\\samis\\domain\\preoperative\\repository\\AnesPreopAssessmentRepository())->findByOperationId($id); $p=(new app\\samis\\domain\\plan\\repository\\AnesthesiaPlanRepository())->findCurrentByOperationId($id); $o=tests\\support\\OperationScheduleFixture::status($id); echo json_encode(['status'=>(!$a&&!$p&&empty($o['visible']))?'absent':'present'], JSON_UNESCAPED_UNICODE);`);}
